dir.build=build
dir.classes=${dir.build}/classes
dir.src=src
dir.alt=alt-src
dir.lib=lib
dir.docs=docs
dir.main=${dir.src}/main
dir.java=${dir.main}/java
dir.resources=${dir.main}/resources
dir.asciiResources=${dir.resources}/ascii
dir.testReport=testReport

scp.user=s467204
scp.host=helios.cs.ifmo.ru
scp.password=bpUq*3874
scp.port=2222
scp.dir=/home/studs/s467204/OPI/lab3

media.sound=quack.wav

env.javaHome= /Users/ipka23/.sdkman/candidates/java
#env.javaVersion=17.0.19-tem
env.javaVersion=21.0.4-tem
env.java = ${env.javaHome}/${env.javaVersion}

team.dir=last3Revisions
team.rev1=1
team.rev2=2
team.rev3=3

