build=build
classes=${build}/classes
src=src
lib=lib
docs=docs
main=${src}/main
java=${main}/java
resources=${main}/resources
asciiResources=${resources}/ascii

user=s467204
host=helios.cs.ifmo.ru
password=bpUq*3874
port=2222
scpDir=/home/studs/s467204/OPI/lab3


sound=quack.wav
