@startuml
object Pokemon
Pokemon : ru.ifmo.se.pokemon
object PhysicalMove
PhysicalMove : ru.ifmo.se.pokemon
object SpecialMove
SpecialMove : ru.ifmo.se.pokemon
object StatusMove
StatusMove : ru.ifmo.se.pokemon




object Miltank
Miltank : pokemons
object Swablu
Swablu : pokemons
object Altaria
Altaria : pokemons
object Honedge
Honedge : pokemons
object Doublade
Doublade : pokemons
object AegislashBlade
AegislashBlade : pokemons



object BrutalSwing
BrutalSwing : moves.physical
object FuryAttack
FuryAttack : moves.physical
object HeadSmash
HeadSmash : moves.physical
object RockSlide
RockSlide : moves.physical
object WakeUpSlap
WakeUpSlap : moves.physical
object Blizzard
Blizzard : moves.special
object DragonBreath
DragonBreath : moves.special
object DreamEater
DreamEater : moves.special
object Confide
Confide : moves.status
object DoubleTeam
DoubleTeam : moves.status
object MetalSound
MetalSound : moves.status


Pokemon <|-- Miltank
Pokemon <|-- Swablu
Swablu <|-- Altaria
Pokemon <|-- Honedge
Honedge <|-- Doublade
Doublade <|-- AegislashBlade

PhysicalMove <|-- BrutalSwing
PhysicalMove <|-- FuryAttack
PhysicalMove <|-- HeadSmash
PhysicalMove <|-- RockSlide
PhysicalMove <|-- WakeUpSlap

SpecialMove <|--  Blizzard
SpecialMove <|--  DragonBreath
SpecialMove <|--  DreamEater

StatusMove <|--  Confide
StatusMove <|--  DoubleTeam
StatusMove <|--  MetalSound

'
'Miltank <-- WakeUpSlap
'Miltank <-- RockSlide
'Miltank <-- Blizzard
'Miltank <-- DoubleTeam
'
'AegislashBlade <-- HeadSmash
'AegislashBlade <-- MetalSound
'AegislashBlade <-- BrutalSwing
'AegislashBlade <-- DoubleTeam

'Doublade <-- MetalSound
'Doublade <-- BrutalSwing
'Doublade <-- DoubleTeam

'
'Honedge <-- BrutalSwing
'Honedge <-- DoubleTeam
'
'Swablu <-- Confide
'Swablu <-- FuryAttack
'Swablu <-- DreamEater
'
'Altaria <-- DragonBreath
'Altaria <-- Confide
'Altaria <-- FuryAttack
'Altaria <-- DreamEater


@enduml